"""Celery tasks: create Confluence knowledge articles from AI-generated RCAs."""

from __future__ import annotations

import logging
from typing import Any

from aiops.celery_app import app
from aiops import config

logger = logging.getLogger(__name__)


def _markdown_to_confluence_storage(md: str) -> str:
    """Very lightweight Markdown → Confluence Storage Format conversion."""
    import re

    lines = md.split("\n")
    out: list[str] = []
    for line in lines:
        # Headings
        if line.startswith("### "):
            out.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("## "):
            out.append(f"<h2>{line[3:]}</h2>")
        elif line.startswith("# "):
            out.append(f"<h1>{line[2:]}</h1>")
        # Bold
        else:
            line = re.sub(r"\*\*(.*?)\*\*", r"<strong>\1</strong>", line)
            # Bullet list
            if line.startswith("- "):
                out.append(f"<li>{line[2:]}</li>")
            else:
                out.append(f"<p>{line}</p>" if line.strip() else "<p> </p>")

    return "\n".join(out)


@app.task(bind=True, max_retries=3, default_retry_delay=60, name="aiops.tasks.confluence_kb.create_kb_article")
def create_kb_article(self, ticket: dict[str, Any], rca_text: str) -> dict[str, Any]:
    """Create a new Confluence page from the RCA when no KB article exists.

    Args:
        ticket: ticket dict (key, summary, category, service).
        rca_text: full RCA text generated by the LLM.

    Returns:
        dict with ``page_id`` and ``page_url``.
    """
    import requests
    from requests.auth import HTTPBasicAuth

    if not config.CONFLUENCE_BASE_URL or not config.JIRA_API_TOKEN:
        logger.warning("Confluence credentials not configured — skipping KB creation")
        return {"page_id": None, "page_url": None}

    ticket_key = ticket.get("key", "N/A")
    summary = ticket.get("summary", "Untitled")
    category = ticket.get("category", "General")
    service = ticket.get("service", "unknown")

    title = f"[RCA] {ticket_key} — {summary[:80]}"
    storage_body = _markdown_to_confluence_storage(rca_text)

    # Wrap in a Confluence info macro header
    page_body = f"""
<ac:structured-macro ac:name="info">
  <ac:rich-text-body>
    <p>Auto-generated RCA by AI Ops for Jira ticket
       <strong>{ticket_key}</strong> ({category} / {service}).
    </p>
  </ac:rich-text-body>
</ac:structured-macro>
{storage_body}
"""

    url = f"{config.CONFLUENCE_BASE_URL}/wiki/rest/api/content"
    auth = HTTPBasicAuth(config.JIRA_USER, config.JIRA_API_TOKEN)

    payload: dict[str, Any] = {
        "type": "page",
        "title": title,
        "space": {"key": config.CONFLUENCE_SPACE_KEY},
        "body": {
            "storage": {
                "value": page_body,
                "representation": "storage",
            }
        },
    }
    if config.CONFLUENCE_PARENT_PAGE_ID:
        payload["ancestors"] = [{"id": config.CONFLUENCE_PARENT_PAGE_ID}]

    try:
        resp = requests.post(url, json=payload, auth=auth, timeout=20)
        resp.raise_for_status()
        data = resp.json()
        page_id = data.get("id")
        webui = data.get("_links", {}).get("webui", "")
        page_url = config.CONFLUENCE_BASE_URL + "/wiki" + webui

        logger.info("Created Confluence page '%s' (id=%s)", title, page_id)

        # Link the new Confluence page back to the Jira ticket
        _link_confluence_to_jira(ticket_key, page_url, title)

        return {"page_id": page_id, "page_url": page_url}
    except Exception as exc:
        logger.error("Failed to create Confluence page: %s", exc)
        raise self.retry(exc=exc)


def _link_confluence_to_jira(ticket_key: str, page_url: str, page_title: str) -> None:
    """Add a remote link on the Jira issue pointing to the new Confluence page."""
    import requests
    from requests.auth import HTTPBasicAuth

    if not config.JIRA_BASE_URL or not config.JIRA_API_TOKEN:
        return

    url = f"{config.JIRA_BASE_URL}/rest/api/3/issue/{ticket_key}/remotelink"
    auth = HTTPBasicAuth(config.JIRA_USER, config.JIRA_API_TOKEN)
    payload = {
        "globalId": f"confluence-rca-{ticket_key}",
        "object": {
            "url": page_url,
            "title": page_title,
            "icon": {
                "url16x16": "https://confluence.atlassian.com/images/logo/confluence_16.png",
                "title": "Confluence Page",
            },
        },
    }
    resp = requests.post(url, json=payload, auth=auth, timeout=15)
    if not resp.ok:
        logger.warning(
            "Could not link Confluence page to Jira %s: %s", ticket_key, resp.text
        )
