"""Celery tasks: send email alerts for log thresholds and Datadog monitor breaches."""

from __future__ import annotations

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

from aiops.celery_app import app
from aiops import config

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# SMTP helper
# ---------------------------------------------------------------------------

def _send_email(subject: str, body_html: str, recipients: list[str] | None = None) -> None:
    to_list = recipients or config.ALERT_EMAIL_RECIPIENTS
    if not to_list:
        logger.warning("No email recipients configured — skipping email")
        return
    if not config.SMTP_USER or not config.SMTP_PASSWORD:
        logger.warning("SMTP credentials not configured — skipping email")
        return

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = config.SMTP_USER
    msg["To"] = ", ".join(to_list)
    msg.attach(MIMEText(body_html, "html"))

    try:
        with smtplib.SMTP(config.SMTP_HOST, config.SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(config.SMTP_USER, config.SMTP_PASSWORD)
            server.sendmail(config.SMTP_USER, to_list, msg.as_string())
        logger.info("Email sent: %s -> %s", subject, to_list)
    except Exception as exc:
        logger.error("Failed to send email: %s", exc)
        raise


# ---------------------------------------------------------------------------
# Celery tasks
# ---------------------------------------------------------------------------

@app.task(bind=True, max_retries=3, default_retry_delay=30, name="aiops.tasks.notify.send_threshold_alert")
def send_threshold_alert(
    self,
    ticket: dict[str, Any],
    error_count: int,
    warn_count: int,
    fatal_count: int,
    top_lines: list[str],
) -> None:
    """Send an email alert when log thresholds are exceeded.

    Args:
        ticket: ticket dict (key, summary, service, env).
        error_count: number of error-level log lines.
        warn_count: number of warning-level log lines.
        fatal_count: number of fatal/critical log lines.
        top_lines: most relevant log excerpts.
    """
    ticket_key = ticket.get("key", "N/A")
    service = ticket.get("service", "unknown")
    env = ticket.get("env", "unknown")

    subject = f"⚠️ AI Ops Alert: Log Threshold Exceeded — {ticket_key} [{service}/{env}]"

    lines_html = "".join(
        f"<li><code>{line[:200]}</code></li>" for line in top_lines
    )

    body = f"""
    <html><body>
    <h2>🚨 Log Threshold Alert</h2>
    <p><strong>Ticket:</strong> {ticket_key} — {ticket.get('summary', '')}</p>
    <p><strong>Service:</strong> {service} | <strong>Env:</strong> {env}</p>
    <table border="1" cellpadding="6" cellspacing="0">
      <tr><th>Metric</th><th>Count</th><th>Threshold</th></tr>
      <tr><td>Errors</td><td>{error_count}</td><td>{config.ERROR_COUNT_THRESHOLD}</td></tr>
      <tr><td>Warnings</td><td>{warn_count}</td><td>{config.WARNING_COUNT_THRESHOLD}</td></tr>
      <tr><td>Fatals</td><td>{fatal_count}</td><td>{config.FATAL_COUNT_THRESHOLD}</td></tr>
    </table>
    <h3>Top Log Lines</h3>
    <ul>{lines_html}</ul>
    <p>Please investigate immediately.</p>
    </body></html>
    """

    try:
        _send_email(subject, body)
    except Exception as exc:
        raise self.retry(exc=exc)


@app.task(bind=True, max_retries=3, default_retry_delay=30, name="aiops.tasks.notify.send_rca_notification")
def send_rca_notification(
    self,
    ticket: dict[str, Any],
    rca_text: str,
) -> None:
    """Email the generated RCA to stakeholders.

    Args:
        ticket: ticket dict.
        rca_text: full RCA markdown text.
    """
    ticket_key = ticket.get("key", "N/A")
    subject = f"📋 AI Ops RCA Ready — {ticket_key}: {ticket.get('summary', '')[:80]}"

    import html as _html

    rca_html = _html.escape(rca_text).replace("\n", "<br>")
    body = f"""
    <html><body>
    <h2>Root Cause Analysis — {ticket_key}</h2>
    <p><strong>Summary:</strong> {ticket.get('summary', '')}</p>
    <p><strong>Priority:</strong> {ticket.get('priority', '')} |
       <strong>Category:</strong> {ticket.get('category', '')}</p>
    <hr/>
    {rca_html}
    <hr/>
    <p><em>Generated by AI Ops Automation System</em></p>
    </body></html>
    """

    try:
        _send_email(subject, body)
    except Exception as exc:
        raise self.retry(exc=exc)


@app.task(bind=True, max_retries=3, default_retry_delay=30, name="aiops.tasks.notify.send_datadog_alert")
def send_datadog_alert(
    self,
    alert_payload: dict[str, Any],
) -> None:
    """Email stakeholders when Datadog signals a monitor threshold breach.

    Args:
        alert_payload: parsed Datadog webhook payload.
    """
    monitor_name = alert_payload.get("monitor_name", "Unknown Monitor")
    metric = alert_payload.get("metric", "")
    value = alert_payload.get("value", "")
    threshold = alert_payload.get("threshold", "")
    screenshot_url = alert_payload.get("snapshot_url", "")
    transition = alert_payload.get("transition", "ALERT")

    subject = f"🔴 Datadog Monitor {transition}: {monitor_name}"

    screenshot_html = (
        f'<p><a href="{screenshot_url}">View Snapshot</a></p>'
        if screenshot_url
        else ""
    )

    body = f"""
    <html><body>
    <h2>🔴 Datadog Monitor Alert</h2>
    <p><strong>Monitor:</strong> {monitor_name}</p>
    <p><strong>Metric:</strong> {metric}</p>
    <p><strong>Current Value:</strong> {value} | <strong>Threshold:</strong> {threshold}</p>
    <p><strong>Transition:</strong> {transition}</p>
    {screenshot_html}
    <pre>{str(alert_payload)[:2000]}</pre>
    <p><em>AI Ops has queued an RCA for this event.</em></p>
    </body></html>
    """

    try:
        _send_email(subject, body)
    except Exception as exc:
        raise self.retry(exc=exc)
